enableGlobalCache: true

enableInlineBuilds: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

logFilters:
  - code: YN0060
    level: discard
  - pattern: "secp256k1@npm:4.0.3 STDERR*"
    level: discard

packageExtensions:
  "@devtools-ds/themes@*":
    peerDependencies:
      "react-dom": "*"
  "@devtools-ds/object-inspector@*":
    peerDependencies:
      "react-dom": "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/telemetry@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/testing-library@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@uniswap/swap-router-contracts@*":
    peerDependencies:
      "hardhat": "*"
  "@uniswap/v3-periphery@*":
    peerDependencies:
      "hardhat": "*"
    peerDependenciesMeta:
      "hardhat":
        optional: true
  "@uniswap/v3-sdk@*":
    peerDependencies:
      "hardhat": "*"
    peerDependenciesMeta:
      "hardhat":
        optional: true
  "@uniswap/v3-staker@*":
    peerDependencies:
      "hardhat": "*"
    peerDependenciesMeta:
      "hardhat":
        optional: true
  "eslint-config-react-app@*":
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
