name: Build (develop)

on:
  push:
    branches:
      - test/action

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: git autocrlf config
        run: git config core.autocrlf false
      - name: git eol config
        run: git config core.eol lf
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: windows-defender
        run: powershell -Command Add-MpPreference -ExclusionPath "."
      - name: install
        run: yarn install --network-timeout 1000000
      - name: build
        run: yarn xy build -v
      - name: cycle
        run: yarn cycle
      - name: build-storybook
        run: yarn build-storybook
