name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
        node: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: install
        run: yarn install --network-timeout 1000000

      - name: compile
        run: yarn xy compile

      - name: lint
        run: yarn xy lint

      - name: deps
        run: yarn xy deps

      - name: cycle
        run: yarn xy cycle

      - name: build-storybook
        run: yarn build-storybook
